In [1]:
import requests
import io

from datetime import datetime, UTC
from loguru import logger
import pandas as pd

In [2]:
URL = "https://dev-internal-api.elmodis.com/scripts/events-summary/data"

### Timestamp testing

No timestamp

In [3]:
resp = requests.get(URL, params={"assets": "210"})
buf = io.BytesIO(resp.content)

pd.read_json(buf)

# correct representation of data

,assetId,category,countAlarms,countWarnings,online,status,timezone,workingDay
0,210,DATA,0,0,Mixed,OK,UTC,2024-03-27
1,210,DATA,0,0,Mixed,OK,UTC,2024-03-28
2,210,DATA,0,0,Mixed,OK,UTC,2024-03-29
3,210,DATA,0,0,Mixed,OK,UTC,2024-03-30
4,210,DATA,0,0,Mixed,OK,UTC,2024-03-31
5,210,DATA,0,0,False,OFFLINE,UTC,2024-04-01
6,210,DATA,0,0,Mixed,OK,UTC,2024-04-02
7,210,DATA,0,0,Mixed,OK,UTC,2024-04-03
8,210,DIAGNOSTICS,0,96,Mixed,WARNING,UTC,2024-03-27
9,210,DIAGNOSTICS,0,96,Mixed,WARNING,UTC,2024-03-28
10,210,DIAGNOSTICS,0,96,Mixed,WARNING,UTC,2024-03-29
11,210,DIAGNOSTICS,0,96,Mixed,WARNING,UTC,2024-03-30
12,210,DIAGNOSTICS,0,96,Mixed,WARNING,UTC,2024-03-31
13,210,DIAGNOSTICS,0,96,False,OFFLINE,UTC,2024-04-01
14,210,DIAGNOSTICS,0,96,Mixed,WARNING,UTC,2024-04-02
15,210,DIAGNOSTICS,0,94,Mixed,WARNING,UTC,2024-04-03
16,210,MACHINE,108,225,Mixed,ALARM,UTC,2024-03-27
17,210,MACHINE,108,224,Mixed,ALARM,UTC,2024-03-28
18,210,MACHINE,108,224,Mixed,ALARM,UTC,2024-03-29
19,210,MACHINE,108,225,Mixed,ALARM,UTC,2024-03-30
20,210,MACHINE,108,224,Mixed,ALARM,UTC,2024-03-31
21,210,MACHINE,78,184,False,OFFLINE,UTC,2024-04-01
22,210,MACHINE,84,193,Mixed,ALARM,UTC,2024-04-02
23,210,MACHINE,107,221,Mixed,ALARM,UTC,2024-04-03
24,210,MAINTENANCE,0,0,Mixed,OK,UTC,2024-03-27
25,210,MAINTENANCE,0,0,Mixed,OK,UTC,2024-03-28
26,210,MAINTENANCE,0,0,Mixed,OK,UTC,2024-03-29
27,210,MAINTENANCE,0,0,Mixed,OK,UTC,2024-03-30
28,210,MAINTENANCE,0,0,Mixed,OK,UTC,2024-03-31
29,210,MAINTENANCE,0,0,False,OFFLINE,UTC,2024-04-01
30,210,MAINTENANCE,0,0,Mixed,OK,UTC,2024-04-02
31,210,MAINTENANCE,0,0,Mixed,OK,UTC,2024-04-03
32,210,SYSTEM,0,0,Mixed,OK,UTC,2024-03-27
33,210,SYSTEM,0,0,Mixed,OK,UTC,2024-03-28
34,210,SYSTEM,0,0,Mixed,OK,UTC,2024-03-29
35,210,SYSTEM,0,0,Mixed,OK,UTC,2024-03-30
36,210,SYSTEM,0,0,Mixed,OK,UTC,2024-03-31
37,210,SYSTEM,0,0,False,OFFLINE,UTC,2024-04-01
38,210,SYSTEM,0,0,Mixed,OK,UTC,2024-04-02
39,210,SYSTEM,0,0,Mixed,OK,UTC,2024-04-03

Set timestamp

In [4]:
start = datetime(2024,4,2, tzinfo=UTC)
end = datetime(2024,4,3,second=1, tzinfo=UTC)
# ok
resp = requests.get(URL, params={"assets": "210", "ts":f"{int(start.timestamp())}:{int(end.timestamp())}"})
buf = io.BytesIO(resp.content)
pd.read_json(buf)

,assetId,category,countAlarms,countWarnings,online,status,timezone,workingDay
0,210,DATA,0,0,Mixed,OK,UTC,2024-04-02
1,210,DATA,0,0,Mixed,OK,UTC,2024-04-03
2,210,DIAGNOSTICS,0,96,Mixed,WARNING,UTC,2024-04-02
3,210,DIAGNOSTICS,0,94,Mixed,WARNING,UTC,2024-04-03
4,210,MACHINE,84,193,Mixed,ALARM,UTC,2024-04-02
5,210,MACHINE,107,221,Mixed,ALARM,UTC,2024-04-03
6,210,MAINTENANCE,0,0,Mixed,OK,UTC,2024-04-02
7,210,MAINTENANCE,0,0,Mixed,OK,UTC,2024-04-03
8,210,SYSTEM,0,0,Mixed,OK,UTC,2024-04-02
9,210,SYSTEM,0,0,Mixed,OK,UTC,2024-04-03

### Category testing

Single Category

In [10]:
start = datetime(2024,4,3, tzinfo=UTC) # utc
end = datetime(2024,4,3,second=1, tzinfo=UTC)
tsStr = f"{int(start.timestamp())}:{int(end.timestamp())}"

resp = requests.get(URL, params={"assets": "210", "category": "MACHINE", "ts": tsStr})

buf = io.BytesIO(resp.content)
pd.read_json(buf)

,assetId,category,countAlarms,countWarnings,online,status,timezone,workingDay
0,210,MACHINE,107,221,Mixed,ALARM,UTC,2024-04-03

Multiple Categories

In [12]:
start = datetime(2024,4,3, tzinfo=UTC) # utc
end = datetime(2024,4,3,second=1, tzinfo=UTC)
tsStr = f"{int(start.timestamp())}:{int(end.timestamp())}"

resp = requests.get(URL, params={"assets": "210", "category": "MACHINE,DIAGNOSTICS", "ts": tsStr})

buf = io.BytesIO(resp.content)
pd.read_json(buf)

,assetId,category,countAlarms,countWarnings,online,status,timezone,workingDay
0,210,DIAGNOSTICS,0,94,Mixed,WARNING,UTC,2024-04-03
1,210,MACHINE,107,221,Mixed,ALARM,UTC,2024-04-03

### Organization/Asset testing

Organization only, single day

In [8]:
start = datetime(2024,4,3, tzinfo=UTC) # utc
end = datetime(2024,4,3,second=1, tzinfo=UTC)
tsStr = f"{int(start.timestamp())}:{int(end.timestamp())}"
resp = requests.get(URL, params={"organization": "1259", "category": "MACHINE", "ts": tsStr})
buf = io.BytesIO(resp.content)
pd.read_json(buf)

,assetId,category,countAlarms,countWarnings,online,status,timezone,workingDay
0,183,MACHINE,0,94,Mixed,WARNING,UTC,2024-04-03
1,189,MACHINE,0,47,Mixed,WARNING,UTC,2024-04-03
2,210,MACHINE,107,221,Mixed,ALARM,UTC,2024-04-03
3,212,MACHINE,107,221,True,ALARM,UTC,2024-04-03
4,220,MACHINE,0,0,True,OK,UTC,2024-04-03
5,223,MACHINE,0,94,True,WARNING,UTC,2024-04-03
6,227,MACHINE,0,0,True,OK,UTC,2024-04-03
7,230,MACHINE,107,221,Mixed,ALARM,UTC,2024-04-03
8,232,MACHINE,0,0,False,OFFLINE,UTC,2024-04-03
9,233,MACHINE,0,94,Mixed,WARNING,UTC,2024-04-03
10,234,MACHINE,0,94,Mixed,WARNING,UTC,2024-04-03
11,248,MACHINE,0,0,True,OK,UTC,2024-04-03
12,249,MACHINE,0,0,True,OK,UTC,2024-04-03
13,254,MACHINE,0,94,Mixed,WARNING,UTC,2024-04-03

Single asset, single day

In [13]:
start = datetime(2024,4,3, tzinfo=UTC) # utc
end = datetime(2024,4,3,second=1, tzinfo=UTC)
tsStr = f"{int(start.timestamp())}:{int(end.timestamp())}"
resp = requests.get(URL, params={"assets": "210", "category": "MACHINE", "ts": tsStr})
buf = io.BytesIO(resp.content)
pd.read_json(buf)

,assetId,category,countAlarms,countWarnings,online,status,timezone,workingDay
0,210,MACHINE,107,221,Mixed,ALARM,UTC,2024-04-03

Multiple asset, single day

In [14]:
start = datetime(2024,4,3, tzinfo=UTC) # utc
end = datetime(2024,4,3,second=1, tzinfo=UTC)
tsStr = f"{int(start.timestamp())}:{int(end.timestamp())}"
resp = requests.get(URL, params={"assets": "210,212", "category": "MACHINE", "ts": tsStr})
buf = io.BytesIO(resp.content)
pd.read_json(buf)

,assetId,category,countAlarms,countWarnings,online,status,timezone,workingDay
0,210,MACHINE,107,221,Mixed,ALARM,UTC,2024-04-03
1,212,MACHINE,107,221,True,ALARM,UTC,2024-04-03

Asset not in organization

In [15]:
start = datetime(2024,4,3, tzinfo=UTC) # utc
end = datetime(2024,4,3,second=1, tzinfo=UTC)

tsStr = f"{int(start.timestamp())}:{int(end.timestamp())}"
resp = requests.get(URL, params={"organization":"1259","assets": "2333", "ts":tsStr})
buf = io.BytesIO(resp.content)
pd.read_json(buf)

#none is ok

Empty DataFrame
Columns: []
Index: []

### Accept testing

Json

In [18]:
resp = requests.get(URL, params={"assets": "210", "category": "MACHINE"}, headers={"accept": "application/json"})
buf = io.BytesIO(resp.content)
pd.read_json(buf)

,assetId,category,countAlarms,countWarnings,online,status,timezone,workingDay
0,210,MACHINE,108,225,Mixed,ALARM,UTC,2024-03-27
1,210,MACHINE,108,224,Mixed,ALARM,UTC,2024-03-28
2,210,MACHINE,108,224,Mixed,ALARM,UTC,2024-03-29
3,210,MACHINE,108,225,Mixed,ALARM,UTC,2024-03-30
4,210,MACHINE,108,224,Mixed,ALARM,UTC,2024-03-31
5,210,MACHINE,78,184,False,OFFLINE,UTC,2024-04-01
6,210,MACHINE,84,193,Mixed,ALARM,UTC,2024-04-02
7,210,MACHINE,107,221,Mixed,ALARM,UTC,2024-04-03

CSV

In [19]:
resp = requests.get(URL, params={"assets": "210", "category":"MACHINE"}, headers={"accept": "text/csv"})
buf = io.BytesIO(resp.content)
pd.read_csv(buf)

,assetId,category,countAlarms,countWarnings,online,status,timezone,workingDay
0,210,MACHINE,108,225,Mixed,ALARM,UTC,2024-03-27
1,210,MACHINE,108,224,Mixed,ALARM,UTC,2024-03-28
2,210,MACHINE,108,224,Mixed,ALARM,UTC,2024-03-29
3,210,MACHINE,108,225,Mixed,ALARM,UTC,2024-03-30
4,210,MACHINE,108,224,Mixed,ALARM,UTC,2024-03-31
5,210,MACHINE,78,184,False,OFFLINE,UTC,2024-04-01
6,210,MACHINE,84,193,Mixed,ALARM,UTC,2024-04-02
7,210,MACHINE,107,221,Mixed,ALARM,UTC,2024-04-03